name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Netr0n07
          password: ${{ secrets.GH_PAT }}

      - name: Build and push (with cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/netr0n07/zadanie2-app:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=99746/zadanie2-app-cache:latest
          cache-to: type=registry,ref=99746/zadanie2-app-cache:latest,mode=max

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/netr0n07/zadanie2-app:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
